/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package datauser.ui;

import datauser.database.User;
import datauser.database.UserModel;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angga
 */
public class UserList extends javax.swing.JFrame {

    private final Object[] tableTitle = {"ID", "First Name", "Last Name", "Username"};
    private UserModel userModel = new UserModel();
    private Object[][] tableData;

    /**
     * Creates new form UserList
     */
    public UserList() {
        initComponents();

        refreshTable();

        buttonAdd.addActionListener((ActionEvent e) -> {
            UserForm formCreate = new UserForm(this, true, "create");
            formCreate.setListenerSave((ActionEvent e1) -> {
                if (userModel.insert(formCreate.getUserData())) {
                    formCreate.dispose();
                    refreshTable();
                }
            });
            formCreate.setVisible(true);
        });

        buttonEdit.addActionListener((ActionEvent e) -> {
            if (tableUser.getSelectedRowCount() > 0) {
                int id = Integer.parseInt(tableUser.getValueAt(tableUser.getSelectedRow(), 0).toString());
                UserForm formEdit = new UserForm(this, true, "edit");
                formEdit.setUserData(userModel.selectById(id));
                formEdit.setListenerSave((ActionEvent e1) -> {
                    User user = formEdit.getUserData();
                    user.setId(id);
                    if (userModel.update(user)) {
                        formEdit.dispose();
                        refreshTable();
                    }
                });
                formEdit.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Please select data user first!");
            }
        });

        buttonDelete.addActionListener((ActionEvent e) -> {
            if (tableUser.getSelectedRowCount() > 0) {
                userModel.delete(Integer.parseInt(tableUser.getValueAt(tableUser.getSelectedRow(), 0).toString()));
                refreshTable();
            } else {
                JOptionPane.showMessageDialog(this, "Please select data user first!");
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableUser = new javax.swing.JTable();
        labelTitle = new javax.swing.JLabel();
        buttonAdd = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Manager");

        tableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Fisrt Name", "Last Name", "Username"
            }
        ));
        jScrollPane1.setViewportView(tableUser);

        labelTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTitle.setText("User List");

        buttonAdd.setText("Add New User");

        buttonEdit.setText("Edit");

        buttonDelete.setText("Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTitle)
                    .addComponent(buttonAdd)
                    .addComponent(buttonEdit)
                    .addComponent(buttonDelete))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JTable tableUser;
    // End of variables declaration//GEN-END:variables

    private void refreshTable() {
        tableData = userModel.selectAllObject();
        tableUser.setModel(new DefaultTableModel(tableData, tableTitle));
    }
}
